int   tabget  ();
int   tabdec  (int n);
int   tabinc  (int n);
void  tabset  (int n);
void  prtstr  (int n_args, ...);
char* wrptype (char *type, char *var);
char* concatv (int n_args, ...);
char* concat  (char *s1,   char *s2);
void  putdef  (char *type, char *var, char *func_name, int n_args, ...);
void  putfun  (char *func_name, int n_args, ...);
